// Automatically @generated by generate_default_licenses.py
package moe.nea.licenseextractificator.builder

/**
 * An automatically generated file for all known SPDX license identifiers.
 * You will need to make use of Kotlins backtick notation for most of the license identifiers.
 * Dots in the license identifiers have been replaced with dashes, as to compliant with the JVM
 * 
 * Data last updated 2022-08-25.
 */
class DefaultLicenses(val licenseBuilder: LicenseBuilder) {
  @Deprecated("Not OSI approved")
  fun `CC-BY-2-5`() =
    licenseBuilder.license("Creative Commons Attribution 2.5 Generic", "https://spdx.org/licenses/CC-BY-2.5.html")

  @Deprecated("Not OSI approved")
  fun `blessing`() =
    licenseBuilder.license("SQLite Blessing", "https://spdx.org/licenses/blessing.html")

  @Deprecated("Not OSI approved")
  fun `APAFML`() =
    licenseBuilder.license("Adobe Postscript AFM License", "https://spdx.org/licenses/APAFML.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-3.0-DE.html")

  fun `MPL-2-0`() =
    licenseBuilder.license("Mozilla Public License 2.0", "https://spdx.org/licenses/MPL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `ANTLR-PD-fallback`() =
    licenseBuilder.license("ANTLR Software Rights Notice with license fallback", "https://spdx.org/licenses/ANTLR-PD-fallback.html")

  @Deprecated("Deprecated License Id")
  fun `AGPL-1-0`() =
    licenseBuilder.license("Affero General Public License v1.0", "https://spdx.org/licenses/AGPL-1.0.html")

  fun `PostgreSQL`() =
    licenseBuilder.license("PostgreSQL License", "https://spdx.org/licenses/PostgreSQL.html")

  @Deprecated("Not OSI approved")
  fun `NIST-PD`() =
    licenseBuilder.license("NIST Public Domain Notice", "https://spdx.org/licenses/NIST-PD.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-2-5`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 2.5 Generic", "https://spdx.org/licenses/CC-BY-ND-2.5.html")

  fun `CATOSL-1-1`() =
    licenseBuilder.license("Computer Associates Trusted Open Source License 1.1", "https://spdx.org/licenses/CATOSL-1.1.html")

  fun `MIT-Modern-Variant`() =
    licenseBuilder.license("MIT License Modern Variant", "https://spdx.org/licenses/MIT-Modern-Variant.html")

  @Deprecated("Not OSI approved")
  fun `Spencer-86`() =
    licenseBuilder.license("Spencer License 86", "https://spdx.org/licenses/Spencer-86.html")

  @Deprecated("Not OSI approved")
  fun `Adobe-Glyph`() =
    licenseBuilder.license("Adobe Glyph List License", "https://spdx.org/licenses/Adobe-Glyph.html")

  @Deprecated("Not OSI approved")
  fun `LPPL-1-3a`() =
    licenseBuilder.license("LaTeX Project Public License v1.3a", "https://spdx.org/licenses/LPPL-1.3a.html")

  @Deprecated("Not OSI approved")
  fun `NBPL-1-0`() =
    licenseBuilder.license("Net Boolean Public License v1", "https://spdx.org/licenses/NBPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `YPL-1-1`() =
    licenseBuilder.license("Yahoo! Public License v1.1", "https://spdx.org/licenses/YPL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `OCCT-PL`() =
    licenseBuilder.license("Open CASCADE Technology Public License", "https://spdx.org/licenses/OCCT-PL.html")

  @Deprecated("Not OSI approved")
  fun `C-UDA-1-0`() =
    licenseBuilder.license("Computational Use of Data Agreement v1.0", "https://spdx.org/licenses/C-UDA-1.0.html")

  @Deprecated("Not OSI approved")
  fun `DSDP`() =
    licenseBuilder.license("DSDP License", "https://spdx.org/licenses/DSDP.html")

  fun `Xnet`() =
    licenseBuilder.license("X.Net License", "https://spdx.org/licenses/Xnet.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0-NL`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 Netherlands", "https://spdx.org/licenses/CC-BY-3.0-NL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-3-0-IGO`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-IGO.html")

  fun `RPL-1-1`() =
    licenseBuilder.license("Reciprocal Public License 1.1", "https://spdx.org/licenses/RPL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-2-1`() =
    licenseBuilder.license("Open LDAP Public License v2.2.1", "https://spdx.org/licenses/OLDAP-2.2.1.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 Germany", "https://spdx.org/licenses/CC-BY-3.0-DE.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 only", "https://spdx.org/licenses/GFDL-1.2-only.html")

  @Deprecated("Not OSI approved")
  fun `App-s2p`() =
    licenseBuilder.license("App::s2p License", "https://spdx.org/licenses/App-s2p.html")

  fun `ECL-1-0`() =
    licenseBuilder.license("Educational Community License v1.0", "https://spdx.org/licenses/ECL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Wsuipa`() =
    licenseBuilder.license("Wsuipa License", "https://spdx.org/licenses/Wsuipa.html")

  fun `Python-2-0`() =
    licenseBuilder.license("Python License 2.0", "https://spdx.org/licenses/Python-2.0.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 only - invariants", "https://spdx.org/licenses/GFDL-1.2-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `SMLNJ`() =
    licenseBuilder.license("Standard ML of New Jersey License", "https://spdx.org/licenses/SMLNJ.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0-with-GCC-exception`() =
    licenseBuilder.license("GNU General Public License v2.0 w/GCC Runtime Library exception", "https://spdx.org/licenses/GPL-2.0-with-GCC-exception.html")

  @Deprecated("Not OSI approved")
  fun `VOSTROM`() =
    licenseBuilder.license("VOSTROM Public License for Open Source", "https://spdx.org/licenses/VOSTROM.html")

  fun `CNRI-Python`() =
    licenseBuilder.license("CNRI Python License", "https://spdx.org/licenses/CNRI-Python.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-2-5`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-2.5.html")

  fun `Intel`() =
    licenseBuilder.license("Intel Open Source License", "https://spdx.org/licenses/Intel.html")

  @Deprecated("Not OSI approved")
  fun `W3C-20150513`() =
    licenseBuilder.license("W3C Software Notice and Document License (2015-05-13)", "https://spdx.org/licenses/W3C-20150513.html")

  @Deprecated("Not OSI approved")
  fun `Zimbra-1-4`() =
    licenseBuilder.license("Zimbra Public License v1.4", "https://spdx.org/licenses/Zimbra-1.4.html")

  @Deprecated("Not OSI approved")
  fun `GL2PS`() =
    licenseBuilder.license("GL2PS License", "https://spdx.org/licenses/GL2PS.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-1-2`() =
    licenseBuilder.license("Open LDAP Public License v1.2", "https://spdx.org/licenses/OLDAP-1.2.html")

  fun `BSD-3-Clause-LBNL`() =
    licenseBuilder.license("Lawrence Berkeley National Labs BSD variant license", "https://spdx.org/licenses/BSD-3-Clause-LBNL.html")

  @Deprecated("Not OSI approved")
  fun `TMate`() =
    licenseBuilder.license("TMate Open Source License", "https://spdx.org/licenses/TMate.html")

  @Deprecated("Not OSI approved")
  fun `FSFAP`() =
    licenseBuilder.license("FSF All Permissive License", "https://spdx.org/licenses/FSFAP.html")

  fun `RPL-1-5`() =
    licenseBuilder.license("Reciprocal Public License 1.5", "https://spdx.org/licenses/RPL-1.5.html")

  @Deprecated("Not OSI approved")
  fun `Aladdin`() =
    licenseBuilder.license("Aladdin Free Public License", "https://spdx.org/licenses/Aladdin.html")

  fun `LGPL-2-0-only`() =
    licenseBuilder.license("GNU Library General Public License v2 only", "https://spdx.org/licenses/LGPL-2.0-only.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-4-0`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 4.0 International", "https://spdx.org/licenses/CC-BY-ND-4.0.html")

  @Deprecated("Not OSI approved")
  fun `Ruby`() =
    licenseBuilder.license("Ruby License", "https://spdx.org/licenses/Ruby.html")

  @Deprecated("Not OSI approved")
  fun `BlueOak-1-0-0`() =
    licenseBuilder.license("Blue Oak Model License 1.0.0", "https://spdx.org/licenses/BlueOak-1.0.0.html")

  @Deprecated("Not OSI approved")
  fun `MIT-CMU`() =
    licenseBuilder.license("CMU License", "https://spdx.org/licenses/MIT-CMU.html")

  @Deprecated("Not OSI approved")
  fun `Beerware`() =
    licenseBuilder.license("Beerware License", "https://spdx.org/licenses/Beerware.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-ND-3.0-DE.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 or later", "https://spdx.org/licenses/GFDL-1.2-or-later.html")

  @Deprecated("Not OSI approved")
  fun `TU-Berlin-1-0`() =
    licenseBuilder.license("Technische Universitaet Berlin License 1.0", "https://spdx.org/licenses/TU-Berlin-1.0.html")

  fun `BSD-1-Clause`() =
    licenseBuilder.license("BSD 1-Clause License", "https://spdx.org/licenses/BSD-1-Clause.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-2-5-AU`() =
    licenseBuilder.license("Creative Commons Attribution 2.5 Australia", "https://spdx.org/licenses/CC-BY-2.5-AU.html")

  @Deprecated("Not OSI approved")
  fun `OML`() =
    licenseBuilder.license("Open Market License", "https://spdx.org/licenses/OML.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-1-3`() =
    licenseBuilder.license("Open LDAP Public License v1.3", "https://spdx.org/licenses/OLDAP-1.3.html")

  @Deprecated("Not OSI approved")
  fun `DOC`() =
    licenseBuilder.license("DOC License", "https://spdx.org/licenses/DOC.html")

  fun `OSL-1-0`() =
    licenseBuilder.license("Open Software License 1.0", "https://spdx.org/licenses/OSL-1.0.html")

  fun `SPL-1-0`() =
    licenseBuilder.license("Sun Public License v1.0", "https://spdx.org/licenses/SPL-1.0.html")

  fun `OSET-PL-2-1`() =
    licenseBuilder.license("OSET Public License version 2.1", "https://spdx.org/licenses/OSET-PL-2.1.html")

  fun `GPL-3-0-only`() =
    licenseBuilder.license("GNU General Public License v3.0 only", "https://spdx.org/licenses/GPL-3.0-only.html")

  fun `Multics`() =
    licenseBuilder.license("Multics License", "https://spdx.org/licenses/Multics.html")

  fun `LGPL-2-1-or-later`() =
    licenseBuilder.license("GNU Lesser General Public License v2.1 or later", "https://spdx.org/licenses/LGPL-2.1-or-later.html")

  fun `LGPL-3-0-only`() =
    licenseBuilder.license("GNU Lesser General Public License v3.0 only", "https://spdx.org/licenses/LGPL-3.0-only.html")

  fun `Naumen`() =
    licenseBuilder.license("Naumen Public License", "https://spdx.org/licenses/Naumen.html")

  fun `BSD-2-Clause-Patent`() =
    licenseBuilder.license("BSD-2-Clause Plus Patent License", "https://spdx.org/licenses/BSD-2-Clause-Patent.html")

  @Deprecated("Not OSI approved")
  fun `CNRI-Jython`() =
    licenseBuilder.license("CNRI Jython License", "https://spdx.org/licenses/CNRI-Jython.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-1-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-1.0.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-1-4`() =
    licenseBuilder.license("Open LDAP Public License v1.4", "https://spdx.org/licenses/OLDAP-1.4.html")

  fun `Artistic-1-0-cl8`() =
    licenseBuilder.license("Artistic License 1.0 w/clause 8", "https://spdx.org/licenses/Artistic-1.0-cl8.html")

  fun `AFL-1-1`() =
    licenseBuilder.license("Academic Free License v1.1", "https://spdx.org/licenses/AFL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `Community-Spec-1-0`() =
    licenseBuilder.license("Community Specification License 1.0", "https://spdx.org/licenses/Community-Spec-1.0.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-no-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 or later - no invariants", "https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0`() =
    licenseBuilder.license("GNU General Public License v2.0 only", "https://spdx.org/licenses/GPL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `MIT-enna`() =
    licenseBuilder.license("enna License", "https://spdx.org/licenses/MIT-enna.html")

  @Deprecated("Not OSI approved")
  fun `OGDL-Taiwan-1-0`() =
    licenseBuilder.license("Taiwan Open Government Data License, version 1.0", "https://spdx.org/licenses/OGDL-Taiwan-1.0.html")

  @Deprecated("Not OSI approved")
  fun `FSFULLR`() =
    licenseBuilder.license("FSF Unlimited License (with License Retention)", "https://spdx.org/licenses/FSFULLR.html")

  fun `MS-RL`() =
    licenseBuilder.license("Microsoft Reciprocal License", "https://spdx.org/licenses/MS-RL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-2-0-UK`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 2.0 England and Wales", "https://spdx.org/licenses/CC-BY-SA-2.0-UK.html")

  @Deprecated("Not OSI approved")
  fun `OFL-1-0-no-RFN`() =
    licenseBuilder.license("SIL Open Font License 1.0 with no Reserved Font Name", "https://spdx.org/licenses/OFL-1.0-no-RFN.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 Unported", "https://spdx.org/licenses/CC-BY-3.0.html")

  fun `QPL-1-0`() =
    licenseBuilder.license("Q Public License 1.0", "https://spdx.org/licenses/QPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `PolyForm-Noncommercial-1-0-0`() =
    licenseBuilder.license("PolyForm Noncommercial License 1.0.0", "https://spdx.org/licenses/PolyForm-Noncommercial-1.0.0.html")

  fun `MPL-1-1`() =
    licenseBuilder.license("Mozilla Public License 1.1", "https://spdx.org/licenses/MPL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-No-Nuclear-Warranty`() =
    licenseBuilder.license("BSD 3-Clause No Nuclear Warranty", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-Warranty.html")

  @Deprecated("Not OSI approved")
  fun `ANTLR-PD`() =
    licenseBuilder.license("ANTLR Software Rights Notice", "https://spdx.org/licenses/ANTLR-PD.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-2-0`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 2.0 Generic", "https://spdx.org/licenses/CC-BY-ND-2.0.html")

  @Deprecated("Not OSI approved")
  fun `MulanPSL-1-0`() =
    licenseBuilder.license("Mulan Permissive Software License, Version 1", "https://spdx.org/licenses/MulanPSL-1.0.html")

  fun `LGPL-2-1-only`() =
    licenseBuilder.license("GNU Lesser General Public License v2.1 only", "https://spdx.org/licenses/LGPL-2.1-only.html")

  @Deprecated("Not OSI approved")
  fun `Net-SNMP`() =
    licenseBuilder.license("Net-SNMP License", "https://spdx.org/licenses/Net-SNMP.html")

  @Deprecated("Deprecated License Id")
  fun `GFDL-1-3`() =
    licenseBuilder.license("GNU Free Documentation License v1.3", "https://spdx.org/licenses/GFDL-1.3.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-2-0+`() =
    licenseBuilder.license("GNU Library General Public License v2 or later", "https://spdx.org/licenses/LGPL-2.0+.html")

  fun `APSL-1-2`() =
    licenseBuilder.license("Apple Public Source License 1.2", "https://spdx.org/licenses/APSL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `Sendmail`() =
    licenseBuilder.license("Sendmail License", "https://spdx.org/licenses/Sendmail.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0-US`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 United States", "https://spdx.org/licenses/CC-BY-3.0-US.html")

  @Deprecated("Not OSI approved")
  fun `Bitstream-Vera`() =
    licenseBuilder.license("Bitstream Vera Font License", "https://spdx.org/licenses/Bitstream-Vera.html")

  @Deprecated("Deprecated License Id")
  fun `eCos-2-0`() =
    licenseBuilder.license("eCos license version 2.0", "https://spdx.org/licenses/eCos-2.0.html")

  @Deprecated("Not OSI approved")
  fun `Python-2-0-1`() =
    licenseBuilder.license("Python License 2.0.1", "https://spdx.org/licenses/Python-2.0.1.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-No-Nuclear-License`() =
    licenseBuilder.license("BSD 3-Clause No Nuclear License", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html")

  @Deprecated("Not OSI approved")
  fun `Rdisc`() =
    licenseBuilder.license("Rdisc License", "https://spdx.org/licenses/Rdisc.html")

  @Deprecated("Not OSI approved")
  fun `LPPL-1-0`() =
    licenseBuilder.license("LaTeX Project Public License v1.0", "https://spdx.org/licenses/LPPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-1`() =
    licenseBuilder.license("Open LDAP Public License v2.1", "https://spdx.org/licenses/OLDAP-2.1.html")

  @Deprecated("Not OSI approved")
  fun `AGPL-1-0-or-later`() =
    licenseBuilder.license("Affero General Public License v1.0 or later", "https://spdx.org/licenses/AGPL-1.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `JasPer-2-0`() =
    licenseBuilder.license("JasPer License", "https://spdx.org/licenses/JasPer-2.0.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-3-0`() =
    licenseBuilder.license("GNU General Public License v3.0 only", "https://spdx.org/licenses/GPL-3.0.html")

  fun `AFL-3-0`() =
    licenseBuilder.license("Academic Free License v3.0", "https://spdx.org/licenses/AFL-3.0.html")

  fun `EUDatagrid`() =
    licenseBuilder.license("EU DataGrid Software License", "https://spdx.org/licenses/EUDatagrid.html")

  @Deprecated("Not OSI approved")
  fun `SGI-B-2-0`() =
    licenseBuilder.license("SGI Free Software License B v2.0", "https://spdx.org/licenses/SGI-B-2.0.html")

  fun `MPL-1-0`() =
    licenseBuilder.license("Mozilla Public License 1.0", "https://spdx.org/licenses/MPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-0`() =
    licenseBuilder.license("Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)", "https://spdx.org/licenses/OLDAP-2.0.html")

  @Deprecated("Not OSI approved")
  fun `NLOD-1-0`() =
    licenseBuilder.license("Norwegian Licence for Open Government Data (NLOD) 1.0", "https://spdx.org/licenses/NLOD-1.0.html")

  @Deprecated("Not OSI approved")
  fun `TOSL`() =
    licenseBuilder.license("Trusster Open Source License", "https://spdx.org/licenses/TOSL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-3-0`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 3.0 Unported", "https://spdx.org/licenses/CC-BY-SA-3.0.html")

  fun `Nokia`() =
    licenseBuilder.license("Nokia Open Source License", "https://spdx.org/licenses/Nokia.html")

  @Deprecated("Not OSI approved")
  fun `Linux-OpenIB`() =
    licenseBuilder.license("Linux Kernel Variant of OpenIB.org license", "https://spdx.org/licenses/Linux-OpenIB.html")

  @Deprecated("Not OSI approved")
  fun `ODbL-1-0`() =
    licenseBuilder.license("Open Data Commons Open Database License v1.0", "https://spdx.org/licenses/ODbL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `SISSL-1-2`() =
    licenseBuilder.license("Sun Industry Standards Source License v1.2", "https://spdx.org/licenses/SISSL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `GD`() =
    licenseBuilder.license("GD License", "https://spdx.org/licenses/GD.html")

  fun `LiLiQ-P-1-1`() =
    licenseBuilder.license("Licence Libre du Qu\u00e9bec \u2013 Permissive version 1.1", "https://spdx.org/licenses/LiLiQ-P-1.1.html")

  @Deprecated("Deprecated License Id")
  fun `BSD-2-Clause-NetBSD`() =
    licenseBuilder.license("BSD 2-Clause NetBSD License", "https://spdx.org/licenses/BSD-2-Clause-NetBSD.html")

  fun `0BSD`() =
    licenseBuilder.license("BSD Zero Clause License", "https://spdx.org/licenses/0BSD.html")

  @Deprecated("Not OSI approved")
  fun `ADSL`() =
    licenseBuilder.license("Amazon Digital Services License", "https://spdx.org/licenses/ADSL.html")

  @Deprecated("Not OSI approved")
  fun `CrystalStacker`() =
    licenseBuilder.license("CrystalStacker License", "https://spdx.org/licenses/CrystalStacker.html")

  fun `Unicode-DFS-2016`() =
    licenseBuilder.license("Unicode License Agreement - Data Files and Software (2016)", "https://spdx.org/licenses/Unicode-DFS-2016.html")

  @Deprecated("Not OSI approved")
  fun `FDK-AAC`() =
    licenseBuilder.license("Fraunhofer FDK AAC Codec Library", "https://spdx.org/licenses/FDK-AAC.html")

  fun `W3C`() =
    licenseBuilder.license("W3C Software Notice and License (2002-12-31)", "https://spdx.org/licenses/W3C.html")

  @Deprecated("Not OSI approved")
  fun `dvipdfm`() =
    licenseBuilder.license("dvipdfm License", "https://spdx.org/licenses/dvipdfm.html")

  fun `VSL-1-0`() =
    licenseBuilder.license("Vovida Software License v1.0", "https://spdx.org/licenses/VSL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Zend-2-0`() =
    licenseBuilder.license("Zend License v2.0", "https://spdx.org/licenses/Zend-2.0.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-1-0+`() =
    licenseBuilder.license("GNU General Public License v1.0 or later", "https://spdx.org/licenses/GPL-1.0+.html")

  fun `PHP-3-01`() =
    licenseBuilder.license("PHP License v3.01", "https://spdx.org/licenses/PHP-3.01.html")

  @Deprecated("Not OSI approved")
  fun `CNRI-Python-GPL-Compatible`() =
    licenseBuilder.license("CNRI Python Open Source GPL Compatible License Agreement", "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html")

  @Deprecated("Not OSI approved")
  fun `Spencer-94`() =
    licenseBuilder.license("Spencer License 94", "https://spdx.org/licenses/Spencer-94.html")

  fun `LiLiQ-R-1-1`() =
    licenseBuilder.license("Licence Libre du Qu\u00e9bec \u2013 R\u00e9ciprocit\u00e9 version 1.1", "https://spdx.org/licenses/LiLiQ-R-1.1.html")

  fun `EPL-1-0`() =
    licenseBuilder.license("Eclipse Public License 1.0", "https://spdx.org/licenses/EPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Elastic-2-0`() =
    licenseBuilder.license("Elastic License 2.0", "https://spdx.org/licenses/Elastic-2.0.html")

  @Deprecated("Not OSI approved")
  fun `Saxpath`() =
    licenseBuilder.license("Saxpath License", "https://spdx.org/licenses/Saxpath.html")

  @Deprecated("Not OSI approved")
  fun `SugarCRM-1-1-3`() =
    licenseBuilder.license("SugarCRM Public License v1.1.3", "https://spdx.org/licenses/SugarCRM-1.1.3.html")

  @Deprecated("Not OSI approved")
  fun `O-UDA-1-0`() =
    licenseBuilder.license("Open Use of Data Agreement v1.0", "https://spdx.org/licenses/O-UDA-1.0.html")

  fun `AAL`() =
    licenseBuilder.license("Attribution Assurance License", "https://spdx.org/licenses/AAL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-2-0-UK`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-UK.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-4-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 4.0 International", "https://spdx.org/licenses/CC-BY-NC-SA-4.0.html")

  fun `CERN-OHL-S-2-0`() =
    licenseBuilder.license("CERN Open Hardware Licence Version 2 - Strongly Reciprocal", "https://spdx.org/licenses/CERN-OHL-S-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-4-0`() =
    licenseBuilder.license("Creative Commons Attribution 4.0 International", "https://spdx.org/licenses/CC-BY-4.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-4-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 4.0 International", "https://spdx.org/licenses/CC-BY-NC-ND-4.0.html")

  @Deprecated("Not OSI approved")
  fun `Condor-1-1`() =
    licenseBuilder.license("Condor Public License v1.1", "https://spdx.org/licenses/Condor-1.1.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-no-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 only - no invariants", "https://spdx.org/licenses/GFDL-1.3-no-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-1-1`() =
    licenseBuilder.license("Open LDAP Public License v1.1", "https://spdx.org/licenses/OLDAP-1.1.html")

  fun `SimPL-2-0`() =
    licenseBuilder.license("Simple Public License 2.0", "https://spdx.org/licenses/SimPL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `psfrag`() =
    licenseBuilder.license("psfrag License", "https://spdx.org/licenses/psfrag.html")

  @Deprecated("Not OSI approved")
  fun `DL-DE-BY-2-0`() =
    licenseBuilder.license("Data licence Germany \u2013 attribution \u2013 version 2.0", "https://spdx.org/licenses/DL-DE-BY-2.0.html")

  @Deprecated("Not OSI approved")
  fun `DRL-1-0`() =
    licenseBuilder.license("Detection Rule License 1.0", "https://spdx.org/licenses/DRL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `zlib-acknowledgement`() =
    licenseBuilder.license("zlib/libpng License with Acknowledgement", "https://spdx.org/licenses/zlib-acknowledgement.html")

  @Deprecated("Deprecated License Id")
  fun `wxWindows`() =
    licenseBuilder.license("wxWindows Library License", "https://spdx.org/licenses/wxWindows.html")

  @Deprecated("Not OSI approved")
  fun `Spencer-99`() =
    licenseBuilder.license("Spencer License 99", "https://spdx.org/licenses/Spencer-99.html")

  @Deprecated("Not OSI approved")
  fun `NAIST-2003`() =
    licenseBuilder.license("Nara Institute of Science and Technology License (2003)", "https://spdx.org/licenses/NAIST-2003.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-3`() =
    licenseBuilder.license("Open LDAP Public License v2.3", "https://spdx.org/licenses/OLDAP-2.3.html")

  fun `OCLC-2-0`() =
    licenseBuilder.license("OCLC Research Public License 2.0", "https://spdx.org/licenses/OCLC-2.0.html")

  @Deprecated("Not OSI approved")
  fun `SCEA`() =
    licenseBuilder.license("SCEA Shared Source License", "https://spdx.org/licenses/SCEA.html")

  @Deprecated("Not OSI approved")
  fun `BitTorrent-1-0`() =
    licenseBuilder.license("BitTorrent Open Source License v1.0", "https://spdx.org/licenses/BitTorrent-1.0.html")

  @Deprecated("Not OSI approved")
  fun `EUPL-1-0`() =
    licenseBuilder.license("European Union Public License 1.0", "https://spdx.org/licenses/EUPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Glide`() =
    licenseBuilder.license("3dfx Glide License", "https://spdx.org/licenses/Glide.html")

  @Deprecated("Not OSI approved")
  fun `FreeImage`() =
    licenseBuilder.license("FreeImage Public License v1.0", "https://spdx.org/licenses/FreeImage.html")

  fun `PHP-3-0`() =
    licenseBuilder.license("PHP License v3.0", "https://spdx.org/licenses/PHP-3.0.html")

  @Deprecated("Not OSI approved")
  fun `libtiff`() =
    licenseBuilder.license("libtiff License", "https://spdx.org/licenses/libtiff.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 only - invariants", "https://spdx.org/licenses/GFDL-1.3-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `mpich2`() =
    licenseBuilder.license("mpich2 License", "https://spdx.org/licenses/mpich2.html")

  @Deprecated("Not OSI approved")
  fun `Bahyph`() =
    licenseBuilder.license("Bahyph License", "https://spdx.org/licenses/Bahyph.html")

  fun `LGPL-2-0-or-later`() =
    licenseBuilder.license("GNU Library General Public License v2 or later", "https://spdx.org/licenses/LGPL-2.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `gnuplot`() =
    licenseBuilder.license("gnuplot License", "https://spdx.org/licenses/gnuplot.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-2-5`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-2.5.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-2-0`() =
    licenseBuilder.license("GNU Library General Public License v2 only", "https://spdx.org/licenses/LGPL-2.0.html")

  fun `MIT-0`() =
    licenseBuilder.license("MIT No Attribution", "https://spdx.org/licenses/MIT-0.html")

  @Deprecated("Not OSI approved")
  fun `CECILL-B`() =
    licenseBuilder.license("CeCILL-B Free Software License Agreement", "https://spdx.org/licenses/CECILL-B.html")

  fun `Artistic-2-0`() =
    licenseBuilder.license("Artistic License 2.0", "https://spdx.org/licenses/Artistic-2.0.html")

  @Deprecated("Not OSI approved")
  fun `TAPR-OHL-1-0`() =
    licenseBuilder.license("TAPR Open Hardware License v1.0", "https://spdx.org/licenses/TAPR-OHL-1.0.html")

  fun `APL-1-0`() =
    licenseBuilder.license("Adaptive Public License 1.0", "https://spdx.org/licenses/APL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `NPL-1-0`() =
    licenseBuilder.license("Netscape Public License v1.0", "https://spdx.org/licenses/NPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `FTL`() =
    licenseBuilder.license("Freetype Project License", "https://spdx.org/licenses/FTL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-2-5`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 2.5 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-2.5.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-3-0-with-GCC-exception`() =
    licenseBuilder.license("GNU General Public License v3.0 w/GCC Runtime Library exception", "https://spdx.org/licenses/GPL-3.0-with-GCC-exception.html")

  @Deprecated("Not OSI approved")
  fun `psutils`() =
    licenseBuilder.license("psutils License", "https://spdx.org/licenses/psutils.html")

  @Deprecated("Not OSI approved")
  fun `NCGL-UK-2-0`() =
    licenseBuilder.license("Non-Commercial Government Licence", "https://spdx.org/licenses/NCGL-UK-2.0.html")

  fun `APSL-1-0`() =
    licenseBuilder.license("Apple Public Source License 1.0", "https://spdx.org/licenses/APSL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `SSH-OpenSSH`() =
    licenseBuilder.license("SSH OpenSSH license", "https://spdx.org/licenses/SSH-OpenSSH.html")

  fun `OGTSL`() =
    licenseBuilder.license("Open Group Test Suite License", "https://spdx.org/licenses/OGTSL.html")

  @Deprecated("Not OSI approved")
  fun `LGPLLR`() =
    licenseBuilder.license("Lesser General Public License For Linguistic Resources", "https://spdx.org/licenses/LGPLLR.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 or later", "https://spdx.org/licenses/GFDL-1.1-or-later.html")

  @Deprecated("Not OSI approved")
  fun `NetCDF`() =
    licenseBuilder.license("NetCDF license", "https://spdx.org/licenses/NetCDF.html")

  @Deprecated("Not OSI approved")
  fun `MakeIndex`() =
    licenseBuilder.license("MakeIndex License", "https://spdx.org/licenses/MakeIndex.html")

  @Deprecated("Not OSI approved")
  fun `NOSL`() =
    licenseBuilder.license("Netizen Open Source License", "https://spdx.org/licenses/NOSL.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-2-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-2.0.html")

  fun `EFL-1-0`() =
    licenseBuilder.license("Eiffel Forum License v1.0", "https://spdx.org/licenses/EFL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `SchemeReport`() =
    licenseBuilder.license("Scheme Language Report License", "https://spdx.org/licenses/SchemeReport.html")

  @Deprecated("Not OSI approved")
  fun `OSL-1-1`() =
    licenseBuilder.license("Open Software License 1.1", "https://spdx.org/licenses/OSL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `BSD-4-Clause-UC`() =
    licenseBuilder.license("BSD-4-Clause (University of California-Specific)", "https://spdx.org/licenses/BSD-4-Clause-UC.html")

  @Deprecated("Not OSI approved")
  fun `Zed`() =
    licenseBuilder.license("Zed License", "https://spdx.org/licenses/Zed.html")

  @Deprecated("Deprecated License Id")
  fun `GFDL-1-2`() =
    licenseBuilder.license("GNU Free Documentation License v1.2", "https://spdx.org/licenses/GFDL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `AGPL-1-0-only`() =
    licenseBuilder.license("Affero General Public License v1.0 only", "https://spdx.org/licenses/AGPL-1.0-only.html")

  @Deprecated("Not OSI approved")
  fun `ImageMagick`() =
    licenseBuilder.license("ImageMagick License", "https://spdx.org/licenses/ImageMagick.html")

  @Deprecated("Not OSI approved")
  fun `CDDL-1-1`() =
    licenseBuilder.license("Common Development and Distribution License 1.1", "https://spdx.org/licenses/CDDL-1.1.html")

  fun `OFL-1-1`() =
    licenseBuilder.license("SIL Open Font License 1.1", "https://spdx.org/licenses/OFL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `CDLA-Sharing-1-0`() =
    licenseBuilder.license("Community Data License Agreement Sharing 1.0", "https://spdx.org/licenses/CDLA-Sharing-1.0.html")

  fun `LPPL-1-3c`() =
    licenseBuilder.license("LaTeX Project Public License v1.3c", "https://spdx.org/licenses/LPPL-1.3c.html")

  @Deprecated("Not OSI approved")
  fun `OpenSSL`() =
    licenseBuilder.license("OpenSSL License", "https://spdx.org/licenses/OpenSSL.html")

  @Deprecated("Not OSI approved")
  fun `FSFUL`() =
    licenseBuilder.license("FSF Unlimited License", "https://spdx.org/licenses/FSFUL.html")

  fun `ECL-2-0`() =
    licenseBuilder.license("Educational Community License v2.0", "https://spdx.org/licenses/ECL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CERN-OHL-1-2`() =
    licenseBuilder.license("CERN Open Hardware Licence v1.2", "https://spdx.org/licenses/CERN-OHL-1.2.html")

  fun `OFL-1-1-RFN`() =
    licenseBuilder.license("SIL Open Font License 1.1 with Reserved Font Name", "https://spdx.org/licenses/OFL-1.1-RFN.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-1-0`() =
    licenseBuilder.license("Creative Commons Attribution 1.0 Generic", "https://spdx.org/licenses/CC-BY-1.0.html")

  fun `OSL-3-0`() =
    licenseBuilder.license("Open Software License 3.0", "https://spdx.org/licenses/OSL-3.0.html")

  @Deprecated("Not OSI approved")
  fun `CDL-1-0`() =
    licenseBuilder.license("Common Documentation License 1.0", "https://spdx.org/licenses/CDL-1.0.html")

  fun `EUPL-1-2`() =
    licenseBuilder.license("European Union Public License 1.2", "https://spdx.org/licenses/EUPL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `Caldera`() =
    licenseBuilder.license("Caldera License", "https://spdx.org/licenses/Caldera.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 3.0 Germany", "https://spdx.org/licenses/CC-BY-ND-3.0-DE.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0-with-bison-exception`() =
    licenseBuilder.license("GNU General Public License v2.0 w/Bison exception", "https://spdx.org/licenses/GPL-2.0-with-bison-exception.html")

  @Deprecated("Not OSI approved")
  fun `BitTorrent-1-1`() =
    licenseBuilder.license("BitTorrent Open Source License v1.1", "https://spdx.org/licenses/BitTorrent-1.1.html")

  @Deprecated("Not OSI approved")
  fun `MIT-feh`() =
    licenseBuilder.license("feh License", "https://spdx.org/licenses/MIT-feh.html")

  @Deprecated("Not OSI approved")
  fun `PDDL-1-0`() =
    licenseBuilder.license("Open Data Commons Public Domain Dedication & License 1.0", "https://spdx.org/licenses/PDDL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 3.0 Germany", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-DE.html")

  @Deprecated("Not OSI approved")
  fun `Libpng`() =
    licenseBuilder.license("libpng License", "https://spdx.org/licenses/Libpng.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-3-0+`() =
    licenseBuilder.license("GNU General Public License v3.0 or later", "https://spdx.org/licenses/GPL-3.0+.html")

  fun `IPL-1-0`() =
    licenseBuilder.license("IBM Public License v1.0", "https://spdx.org/licenses/IPL-1.0.html")

  fun `CERN-OHL-W-2-0`() =
    licenseBuilder.license("CERN Open Hardware Licence Version 2 - Weakly Reciprocal", "https://spdx.org/licenses/CERN-OHL-W-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CPOL-1-02`() =
    licenseBuilder.license("Code Project Open License 1.02", "https://spdx.org/licenses/CPOL-1.02.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0-with-font-exception`() =
    licenseBuilder.license("GNU General Public License v2.0 w/Font exception", "https://spdx.org/licenses/GPL-2.0-with-font-exception.html")

  fun `ZPL-2-0`() =
    licenseBuilder.license("Zope Public License 2.0", "https://spdx.org/licenses/ZPL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `YPL-1-0`() =
    licenseBuilder.license("Yahoo! Public License v1.0", "https://spdx.org/licenses/YPL-1.0.html")

  fun `Sleepycat`() =
    licenseBuilder.license("Sleepycat License", "https://spdx.org/licenses/Sleepycat.html")

  @Deprecated("Not OSI approved")
  fun `NTP-0`() =
    licenseBuilder.license("NTP No Attribution", "https://spdx.org/licenses/NTP-0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-1-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Unicode-DFS-2015`() =
    licenseBuilder.license("Unicode License Agreement - Data Files and Software (2015)", "https://spdx.org/licenses/Unicode-DFS-2015.html")

  @Deprecated("Not OSI approved")
  fun `Cube`() =
    licenseBuilder.license("Cube License", "https://spdx.org/licenses/Cube.html")

  @Deprecated("Not OSI approved")
  fun `copyleft-next-0-3-0`() =
    licenseBuilder.license("copyleft-next 0.3.0", "https://spdx.org/licenses/copyleft-next-0.3.0.html")

  fun `RSCPL`() =
    licenseBuilder.license("Ricoh Source Code Public License", "https://spdx.org/licenses/RSCPL.html")

  @Deprecated("Deprecated License Id")
  fun `Nunit`() =
    licenseBuilder.license("Nunit License", "https://spdx.org/licenses/Nunit.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 only", "https://spdx.org/licenses/GFDL-1.3-only.html")

  @Deprecated("Not OSI approved")
  fun `libpng-2-0`() =
    licenseBuilder.license("PNG Reference Library version 2", "https://spdx.org/licenses/libpng-2.0.html")

  @Deprecated("Not OSI approved")
  fun `Baekmuk`() =
    licenseBuilder.license("Baekmuk License", "https://spdx.org/licenses/Baekmuk.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-2-5`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 2.5 Generic", "https://spdx.org/licenses/CC-BY-SA-2.5.html")

  @Deprecated("Not OSI approved")
  fun `RHeCos-1-1`() =
    licenseBuilder.license("Red Hat eCos Public License v1.1", "https://spdx.org/licenses/RHeCos-1.1.html")

  fun `EFL-2-0`() =
    licenseBuilder.license("Eiffel Forum License v2.0", "https://spdx.org/licenses/EFL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `MTLL`() =
    licenseBuilder.license("Matrix Template Library License", "https://spdx.org/licenses/MTLL.html")

  fun `ISC`() =
    licenseBuilder.license("ISC License", "https://spdx.org/licenses/ISC.html")

  @Deprecated("Not OSI approved")
  fun `LAL-1-3`() =
    licenseBuilder.license("Licence Art Libre 1.3", "https://spdx.org/licenses/LAL-1.3.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 or later", "https://spdx.org/licenses/GFDL-1.3-or-later.html")

  @Deprecated("Not OSI approved")
  fun `RSA-MD`() =
    licenseBuilder.license("RSA Message-Digest License", "https://spdx.org/licenses/RSA-MD.html")

  @Deprecated("Not OSI approved")
  fun `AMDPLPA`() =
    licenseBuilder.license("AMD's plpa_map.c License", "https://spdx.org/licenses/AMDPLPA.html")

  fun `IPA`() =
    licenseBuilder.license("IPA Font License", "https://spdx.org/licenses/IPA.html")

  @Deprecated("Not OSI approved")
  fun `NPL-1-1`() =
    licenseBuilder.license("Netscape Public License v1.1", "https://spdx.org/licenses/NPL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `eGenix`() =
    licenseBuilder.license("eGenix.com Public License 1.1.0", "https://spdx.org/licenses/eGenix.html")

  @Deprecated("Not OSI approved")
  fun `xpp`() =
    licenseBuilder.license("XPP License", "https://spdx.org/licenses/xpp.html")

  @Deprecated("Not OSI approved")
  fun `MIT-advertising`() =
    licenseBuilder.license("Enlightenment License (e16)", "https://spdx.org/licenses/MIT-advertising.html")

  @Deprecated("Not OSI approved")
  fun `GPL-1-0-only`() =
    licenseBuilder.license("GNU General Public License v1.0 only", "https://spdx.org/licenses/GPL-1.0-only.html")

  @Deprecated("Not OSI approved")
  fun `HTMLTIDY`() =
    licenseBuilder.license("HTML Tidy License", "https://spdx.org/licenses/HTMLTIDY.html")

  @Deprecated("Not OSI approved")
  fun `OGL-UK-2-0`() =
    licenseBuilder.license("Open Government Licence v2.0", "https://spdx.org/licenses/OGL-UK-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-1-0`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 1.0 Generic", "https://spdx.org/licenses/CC-BY-ND-1.0.html")

  @Deprecated("Not OSI approved")
  fun `NIST-PD-fallback`() =
    licenseBuilder.license("NIST Public Domain Notice with license fallback", "https://spdx.org/licenses/NIST-PD-fallback.html")

  @Deprecated("Not OSI approved")
  fun `BSD-Source-Code`() =
    licenseBuilder.license("BSD Source Code Attribution", "https://spdx.org/licenses/BSD-Source-Code.html")

  @Deprecated("Not OSI approved")
  fun `X11`() =
    licenseBuilder.license("X11 License", "https://spdx.org/licenses/X11.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-Attribution`() =
    licenseBuilder.license("BSD with attribution", "https://spdx.org/licenses/BSD-3-Clause-Attribution.html")

  @Deprecated("Not OSI approved")
  fun `Plexus`() =
    licenseBuilder.license("Plexus Classworlds License", "https://spdx.org/licenses/Plexus.html")

  @Deprecated("Not OSI approved")
  fun `HaskellReport`() =
    licenseBuilder.license("Haskell Language Report License", "https://spdx.org/licenses/HaskellReport.html")

  @Deprecated("Not OSI approved")
  fun `NRL`() =
    licenseBuilder.license("NRL License", "https://spdx.org/licenses/NRL.html")

  @Deprecated("Not OSI approved")
  fun `Glulxe`() =
    licenseBuilder.license("Glulxe License", "https://spdx.org/licenses/Glulxe.html")

  @Deprecated("Not OSI approved")
  fun `AML`() =
    licenseBuilder.license("Apple MIT License", "https://spdx.org/licenses/AML.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-2-0`() =
    licenseBuilder.license("Creative Commons Attribution 2.0 Generic", "https://spdx.org/licenses/CC-BY-2.0.html")

  fun `EPL-2-0`() =
    licenseBuilder.license("Eclipse Public License 2.0", "https://spdx.org/licenses/EPL-2.0.html")

  fun `OFL-1-1-no-RFN`() =
    licenseBuilder.license("SIL Open Font License 1.1 with no Reserved Font Name", "https://spdx.org/licenses/OFL-1.1-no-RFN.html")

  @Deprecated("Not OSI approved")
  fun `Sendmail-8-23`() =
    licenseBuilder.license("Sendmail License 8.23", "https://spdx.org/licenses/Sendmail-8.23.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-no-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 or later - no invariants", "https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.html")

  fun `Apache-2-0`() =
    licenseBuilder.license("Apache License 2.0", "https://spdx.org/licenses/Apache-2.0.html")

  @Deprecated("Not OSI approved")
  fun `WTFPL`() =
    licenseBuilder.license("Do What The F*ck You Want To Public License", "https://spdx.org/licenses/WTFPL.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-no-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 only - no invariants", "https://spdx.org/licenses/GFDL-1.1-no-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `OGC-1-0`() =
    licenseBuilder.license("OGC Software License, Version 1.0", "https://spdx.org/licenses/OGC-1.0.html")

  fun `BSL-1-0`() =
    licenseBuilder.license("Boost Software License 1.0", "https://spdx.org/licenses/BSL-1.0.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0-with-autoconf-exception`() =
    licenseBuilder.license("GNU General Public License v2.0 w/Autoconf exception", "https://spdx.org/licenses/GPL-2.0-with-autoconf-exception.html")

  @Deprecated("Not OSI approved")
  fun `CECILL-C`() =
    licenseBuilder.license("CeCILL-C Free Software License Agreement", "https://spdx.org/licenses/CECILL-C.html")

  @Deprecated("Not OSI approved")
  fun `ICU`() =
    licenseBuilder.license("ICU License", "https://spdx.org/licenses/ICU.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-no-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 or later - no invariants", "https://spdx.org/licenses/GFDL-1.3-no-invariants-or-later.html")

  @Deprecated("Not OSI approved")
  fun `Borceux`() =
    licenseBuilder.license("Borceux license", "https://spdx.org/licenses/Borceux.html")

  fun `UPL-1-0`() =
    licenseBuilder.license("Universal Permissive License v1.0", "https://spdx.org/licenses/UPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-3-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.3 or later - invariants", "https://spdx.org/licenses/GFDL-1.3-invariants-or-later.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-2`() =
    licenseBuilder.license("Open LDAP Public License v2.2", "https://spdx.org/licenses/OLDAP-2.2.html")

  @Deprecated("Not OSI approved")
  fun `Afmparse`() =
    licenseBuilder.license("Afmparse License", "https://spdx.org/licenses/Afmparse.html")

  fun `LGPL-3-0-or-later`() =
    licenseBuilder.license("GNU Lesser General Public License v3.0 or later", "https://spdx.org/licenses/LGPL-3.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `CC-PDDC`() =
    licenseBuilder.license("Creative Commons Public Domain Dedication and Certification", "https://spdx.org/licenses/CC-PDDC.html")

  @Deprecated("Not OSI approved")
  fun `etalab-2-0`() =
    licenseBuilder.license("Etalab Open License 2.0", "https://spdx.org/licenses/etalab-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-3-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-3.0.html")

  @Deprecated("Not OSI approved")
  fun `BSD-Protection`() =
    licenseBuilder.license("BSD Protection License", "https://spdx.org/licenses/BSD-Protection.html")

  @Deprecated("Not OSI approved")
  fun `Linux-man-pages-copyleft`() =
    licenseBuilder.license("Linux man-pages Copyleft", "https://spdx.org/licenses/Linux-man-pages-copyleft.html")

  @Deprecated("Not OSI approved")
  fun `ODC-By-1-0`() =
    licenseBuilder.license("Open Data Commons Attribution License v1.0", "https://spdx.org/licenses/ODC-By-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-3-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-ND-3.0.html")

  @Deprecated("Not OSI approved")
  fun `SGI-B-1-1`() =
    licenseBuilder.license("SGI Free Software License B v1.1", "https://spdx.org/licenses/SGI-B-1.1.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-3-0-DE`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 3.0 Germany", "https://spdx.org/licenses/CC-BY-SA-3.0-DE.html")

  fun `CPAL-1-0`() =
    licenseBuilder.license("Common Public Attribution License 1.0", "https://spdx.org/licenses/CPAL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `curl`() =
    licenseBuilder.license("curl License", "https://spdx.org/licenses/curl.html")

  fun `NCSA`() =
    licenseBuilder.license("University of Illinois/NCSA Open Source License", "https://spdx.org/licenses/NCSA.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-Open-MPI`() =
    licenseBuilder.license("BSD 3-Clause Open MPI variant", "https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html")

  fun `AGPL-3-0-or-later`() =
    licenseBuilder.license("GNU Affero General Public License v3.0 or later", "https://spdx.org/licenses/AGPL-3.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `Qhull`() =
    licenseBuilder.license("Qhull License", "https://spdx.org/licenses/Qhull.html")

  @Deprecated("Not OSI approved")
  fun `SNIA`() =
    licenseBuilder.license("SNIA Public License 1.1", "https://spdx.org/licenses/SNIA.html")

  @Deprecated("Not OSI approved")
  fun `copyleft-next-0-3-1`() =
    licenseBuilder.license("copyleft-next 0.3.1", "https://spdx.org/licenses/copyleft-next-0.3.1.html")

  @Deprecated("Not OSI approved")
  fun `GLWTPL`() =
    licenseBuilder.license("Good Luck With That Public License", "https://spdx.org/licenses/GLWTPL.html")

  @Deprecated("Not OSI approved")
  fun `PolyForm-Small-Business-1-0-0`() =
    licenseBuilder.license("PolyForm Small Business License 1.0.0", "https://spdx.org/licenses/PolyForm-Small-Business-1.0.0.html")

  fun `APSL-1-1`() =
    licenseBuilder.license("Apple Public Source License 1.1", "https://spdx.org/licenses/APSL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-ND-2-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-ND-2.0.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-3-0-with-autoconf-exception`() =
    licenseBuilder.license("GNU General Public License v3.0 w/Autoconf exception", "https://spdx.org/licenses/GPL-3.0-with-autoconf-exception.html")

  @Deprecated("Not OSI approved")
  fun `IBM-pibs`() =
    licenseBuilder.license("IBM PowerPC Initialization and Boot Software", "https://spdx.org/licenses/IBM-pibs.html")

  fun `SISSL`() =
    licenseBuilder.license("Sun Industry Standards Source License v1.1", "https://spdx.org/licenses/SISSL.html")

  @Deprecated("Deprecated License Id")
  fun `BSD-2-Clause-FreeBSD`() =
    licenseBuilder.license("BSD 2-Clause FreeBSD License", "https://spdx.org/licenses/BSD-2-Clause-FreeBSD.html")

  @Deprecated("Not OSI approved")
  fun `COIL-1-0`() =
    licenseBuilder.license("Copyfree Open Innovation License", "https://spdx.org/licenses/COIL-1.0.html")

  fun `NASA-1-3`() =
    licenseBuilder.license("NASA Open Source Agreement 1.3", "https://spdx.org/licenses/NASA-1.3.html")

  fun `Apache-1-1`() =
    licenseBuilder.license("Apache License 1.1", "https://spdx.org/licenses/Apache-1.1.html")

  @Deprecated("Not OSI approved")
  fun `NICTA-1-0`() =
    licenseBuilder.license("NICTA Public Software License, Version 1.0", "https://spdx.org/licenses/NICTA-1.0.html")

  @Deprecated("Not OSI approved")
  fun `mpi-permissive`() =
    licenseBuilder.license("mpi Permissive License", "https://spdx.org/licenses/mpi-permissive.html")

  fun `LPL-1-0`() =
    licenseBuilder.license("Lucent Public License Version 1.0", "https://spdx.org/licenses/LPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `MIT-open-group`() =
    licenseBuilder.license("MIT Open Group variant", "https://spdx.org/licenses/MIT-open-group.html")

  @Deprecated("Not OSI approved")
  fun `NLOD-2-0`() =
    licenseBuilder.license("Norwegian Licence for Open Government Data (NLOD) 2.0", "https://spdx.org/licenses/NLOD-2.0.html")

  fun `GPL-2-0-only`() =
    licenseBuilder.license("GNU General Public License v2.0 only", "https://spdx.org/licenses/GPL-2.0-only.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-0-1`() =
    licenseBuilder.license("Open LDAP Public License v2.0.1", "https://spdx.org/licenses/OLDAP-2.0.1.html")

  fun `CERN-OHL-P-2-0`() =
    licenseBuilder.license("CERN Open Hardware Licence Version 2 - Permissive", "https://spdx.org/licenses/CERN-OHL-P-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC0-1-0`() =
    licenseBuilder.license("Creative Commons Zero v1.0 Universal", "https://spdx.org/licenses/CC0-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Abstyles`() =
    licenseBuilder.license("Abstyles License", "https://spdx.org/licenses/Abstyles.html")

  @Deprecated("Deprecated License Id")
  fun `AGPL-3-0`() =
    licenseBuilder.license("GNU Affero General Public License v3.0", "https://spdx.org/licenses/AGPL-3.0.html")

  fun `CECILL-2-1`() =
    licenseBuilder.license("CeCILL Free Software License Agreement v2.1", "https://spdx.org/licenses/CECILL-2.1.html")

  fun `CAL-1-0-Combined-Work-Exception`() =
    licenseBuilder.license("Cryptographic Autonomy License 1.0 (Combined Work Exception)", "https://spdx.org/licenses/CAL-1.0-Combined-Work-Exception.html")

  @Deprecated("Not OSI approved")
  fun `Adobe-2006`() =
    licenseBuilder.license("Adobe Systems Incorporated Source Code License Agreement", "https://spdx.org/licenses/Adobe-2006.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-no-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 only - no invariants", "https://spdx.org/licenses/GFDL-1.2-no-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `OGL-UK-3-0`() =
    licenseBuilder.license("Open Government Licence v3.0", "https://spdx.org/licenses/OGL-UK-3.0.html")

  fun `Jam`() =
    licenseBuilder.license("Jam License", "https://spdx.org/licenses/Jam.html")

  fun `APSL-2-0`() =
    licenseBuilder.license("Apple Public Source License 2.0", "https://spdx.org/licenses/APSL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `LPPL-1-2`() =
    licenseBuilder.license("LaTeX Project Public License v1.2", "https://spdx.org/licenses/LPPL-1.2.html")

  fun `CPL-1-0`() =
    licenseBuilder.license("Common Public License 1.0", "https://spdx.org/licenses/CPL-1.0.html")

  fun `OSL-2-0`() =
    licenseBuilder.license("Open Software License 2.0", "https://spdx.org/licenses/OSL-2.0.html")

  fun `Artistic-1-0`() =
    licenseBuilder.license("Artistic License 1.0", "https://spdx.org/licenses/Artistic-1.0.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-7`() =
    licenseBuilder.license("Open LDAP Public License v2.7", "https://spdx.org/licenses/OLDAP-2.7.html")

  fun `AFL-2-1`() =
    licenseBuilder.license("Academic Free License v2.1", "https://spdx.org/licenses/AFL-2.1.html")

  @Deprecated("Not OSI approved")
  fun `ErlPL-1-1`() =
    licenseBuilder.license("Erlang Public License v1.1", "https://spdx.org/licenses/ErlPL-1.1.html")

  fun `LiLiQ-Rplus-1-1`() =
    licenseBuilder.license("Licence Libre du Qu\u00e9bec \u2013 R\u00e9ciprocit\u00e9 forte version 1.1", "https://spdx.org/licenses/LiLiQ-Rplus-1.1.html")

  fun `Motosoto`() =
    licenseBuilder.license("Motosoto License", "https://spdx.org/licenses/Motosoto.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-2-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 2.0 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-2.0.html")

  fun `MulanPSL-2-0`() =
    licenseBuilder.license("Mulan Permissive Software License, Version 2", "https://spdx.org/licenses/MulanPSL-2.0.html")

  fun `RPSL-1-0`() =
    licenseBuilder.license("RealNetworks Public Source License v1.0", "https://spdx.org/licenses/RPSL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Parity-6-0-0`() =
    licenseBuilder.license("The Parity Public License 6.0.0", "https://spdx.org/licenses/Parity-6.0.0.html")

  @Deprecated("Not OSI approved")
  fun `LPPL-1-1`() =
    licenseBuilder.license("LaTeX Project Public License v1.1", "https://spdx.org/licenses/LPPL-1.1.html")

  fun `Frameworx-1-0`() =
    licenseBuilder.license("Frameworx Open License 1.0", "https://spdx.org/licenses/Frameworx-1.0.html")

  @Deprecated("Not OSI approved")
  fun `JSON`() =
    licenseBuilder.license("JSON License", "https://spdx.org/licenses/JSON.html")

  fun `MS-PL`() =
    licenseBuilder.license("Microsoft Public License", "https://spdx.org/licenses/MS-PL.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-No-Military-License`() =
    licenseBuilder.license("BSD 3-Clause No Military License", "https://spdx.org/licenses/BSD-3-Clause-No-Military-License.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-Modification`() =
    licenseBuilder.license("BSD 3-Clause Modification", "https://spdx.org/licenses/BSD-3-Clause-Modification.html")

  @Deprecated("Not OSI approved")
  fun `OGL-UK-1-0`() =
    licenseBuilder.license("Open Government Licence v1.0", "https://spdx.org/licenses/OGL-UK-1.0.html")

  fun `EUPL-1-1`() =
    licenseBuilder.license("European Union Public License 1.1", "https://spdx.org/licenses/EUPL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `bzip2-1-0-6`() =
    licenseBuilder.license("bzip2 and libbzip2 License v1.0.6", "https://spdx.org/licenses/bzip2-1.0.6.html")

  @Deprecated("Not OSI approved")
  fun `Leptonica`() =
    licenseBuilder.license("Leptonica License", "https://spdx.org/licenses/Leptonica.html")

  @Deprecated("Not OSI approved")
  fun `Newsletr`() =
    licenseBuilder.license("Newsletr License", "https://spdx.org/licenses/Newsletr.html")

  fun `AGPL-3-0-only`() =
    licenseBuilder.license("GNU Affero General Public License v3.0 only", "https://spdx.org/licenses/AGPL-3.0-only.html")

  @Deprecated("Not OSI approved")
  fun `MITNFA`() =
    licenseBuilder.license("MIT +no-false-attribs license", "https://spdx.org/licenses/MITNFA.html")

  @Deprecated("Not OSI approved")
  fun `Zimbra-1-3`() =
    licenseBuilder.license("Zimbra Public License v1.3", "https://spdx.org/licenses/Zimbra-1.3.html")

  fun `NGPL`() =
    licenseBuilder.license("Nethack General Public License", "https://spdx.org/licenses/NGPL.html")

  @Deprecated("Not OSI approved")
  fun `Crossword`() =
    licenseBuilder.license("Crossword License", "https://spdx.org/licenses/Crossword.html")

  @Deprecated("Not OSI approved")
  fun `Mup`() =
    licenseBuilder.license("Mup License", "https://spdx.org/licenses/Mup.html")

  @Deprecated("Not OSI approved")
  fun `SSH-short`() =
    licenseBuilder.license("SSH short notice", "https://spdx.org/licenses/SSH-short.html")

  @Deprecated("Not OSI approved")
  fun `mplus`() =
    licenseBuilder.license("mplus Font License", "https://spdx.org/licenses/mplus.html")

  fun `LPL-1-02`() =
    licenseBuilder.license("Lucent Public License v1.02", "https://spdx.org/licenses/LPL-1.02.html")

  @Deprecated("Not OSI approved")
  fun `OFL-1-0-RFN`() =
    licenseBuilder.license("SIL Open Font License 1.0 with Reserved Font Name", "https://spdx.org/licenses/OFL-1.0-RFN.html")

  @Deprecated("Not OSI approved")
  fun `LAL-1-2`() =
    licenseBuilder.license("Licence Art Libre 1.2", "https://spdx.org/licenses/LAL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `CERN-OHL-1-1`() =
    licenseBuilder.license("CERN Open Hardware Licence v1.1", "https://spdx.org/licenses/CERN-OHL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-2-1-JP`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 2.1 Japan", "https://spdx.org/licenses/CC-BY-SA-2.1-JP.html")

  @Deprecated("Not OSI approved")
  fun `AMPAS`() =
    licenseBuilder.license("Academy of Motion Picture Arts and Sciences BSD", "https://spdx.org/licenses/AMPAS.html")

  @Deprecated("Not OSI approved")
  fun `Arphic-1999`() =
    licenseBuilder.license("Arphic Public License", "https://spdx.org/licenses/Arphic-1999.html")

  @Deprecated("Not OSI approved")
  fun `iMatix`() =
    licenseBuilder.license("iMatix Standard Function Library Agreement", "https://spdx.org/licenses/iMatix.html")

  @Deprecated("Not OSI approved")
  fun `BUSL-1-1`() =
    licenseBuilder.license("Business Source License 1.1", "https://spdx.org/licenses/BUSL-1.1.html")

  @Deprecated("Not OSI approved")
  fun `Info-ZIP`() =
    licenseBuilder.license("Info-ZIP License", "https://spdx.org/licenses/Info-ZIP.html")

  @Deprecated("Not OSI approved")
  fun `Vim`() =
    licenseBuilder.license("Vim License", "https://spdx.org/licenses/Vim.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-2-0-FR`() =
    licenseBuilder.license("Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France", "https://spdx.org/licenses/CC-BY-NC-SA-2.0-FR.html")

  @Deprecated("Deprecated License Id")
  fun `GFDL-1-1`() =
    licenseBuilder.license("GNU Free Documentation License v1.1", "https://spdx.org/licenses/GFDL-1.1.html")

  @Deprecated("Deprecated License Id")
  fun `StandardML-NJ`() =
    licenseBuilder.license("Standard ML of New Jersey License", "https://spdx.org/licenses/StandardML-NJ.html")

  @Deprecated("Not OSI approved")
  fun `Interbase-1-0`() =
    licenseBuilder.license("Interbase Public License v1.0", "https://spdx.org/licenses/Interbase-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Hippocratic-2-1`() =
    licenseBuilder.license("Hippocratic License 2.1", "https://spdx.org/licenses/Hippocratic-2.1.html")

  fun `HPND`() =
    licenseBuilder.license("Historical Permission Notice and Disclaimer", "https://spdx.org/licenses/HPND.html")

  @Deprecated("Not OSI approved")
  fun `FreeBSD-DOC`() =
    licenseBuilder.license("FreeBSD Documentation License", "https://spdx.org/licenses/FreeBSD-DOC.html")

  @Deprecated("Not OSI approved")
  fun `Imlib2`() =
    licenseBuilder.license("Imlib2 License", "https://spdx.org/licenses/Imlib2.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-Clear`() =
    licenseBuilder.license("BSD 3-Clause Clear License", "https://spdx.org/licenses/BSD-3-Clause-Clear.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-ND-3-0`() =
    licenseBuilder.license("Creative Commons Attribution No Derivatives 3.0 Unported", "https://spdx.org/licenses/CC-BY-ND-3.0.html")

  @Deprecated("Not OSI approved")
  fun `Eurosym`() =
    licenseBuilder.license("Eurosym License", "https://spdx.org/licenses/Eurosym.html")

  @Deprecated("Not OSI approved")
  fun `CECILL-1-1`() =
    licenseBuilder.license("CeCILL Free Software License Agreement v1.1", "https://spdx.org/licenses/CECILL-1.1.html")

  fun `CUA-OPL-1-0`() =
    licenseBuilder.license("CUA Office Public License v1.0", "https://spdx.org/licenses/CUA-OPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `HPND-sell-variant`() =
    licenseBuilder.license("Historical Permission Notice and Disclaimer - sell variant", "https://spdx.org/licenses/HPND-sell-variant.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-1-0`() =
    licenseBuilder.license("GNU General Public License v1.0 only", "https://spdx.org/licenses/GPL-1.0.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0+`() =
    licenseBuilder.license("GNU General Public License v2.0 or later", "https://spdx.org/licenses/GPL-2.0+.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-3-0`() =
    licenseBuilder.license("GNU Lesser General Public License v3.0 only", "https://spdx.org/licenses/LGPL-3.0.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-2-1`() =
    licenseBuilder.license("GNU Lesser General Public License v2.1 only", "https://spdx.org/licenses/LGPL-2.1.html")

  @Deprecated("Not OSI approved")
  fun `Apache-1-0`() =
    licenseBuilder.license("Apache License 1.0", "https://spdx.org/licenses/Apache-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0-AT`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 Austria", "https://spdx.org/licenses/CC-BY-3.0-AT.html")

  @Deprecated("Not OSI approved")
  fun `OPUBL-1-0`() =
    licenseBuilder.license("Open Publication License v1.0", "https://spdx.org/licenses/OPUBL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `XFree86-1-1`() =
    licenseBuilder.license("XFree86 License 1.1", "https://spdx.org/licenses/XFree86-1.1.html")

  fun `Watcom-1-0`() =
    licenseBuilder.license("Sybase Open Watcom Public License 1.0", "https://spdx.org/licenses/Watcom-1.0.html")

  fun `OLDAP-2-8`() =
    licenseBuilder.license("Open LDAP Public License v2.8", "https://spdx.org/licenses/OLDAP-2.8.html")

  fun `MIT`() =
    licenseBuilder.license("MIT License", "https://spdx.org/licenses/MIT.html")

  @Deprecated("Not OSI approved")
  fun `Intel-ACPI`() =
    licenseBuilder.license("Intel ACPI Software License Agreement", "https://spdx.org/licenses/Intel-ACPI.html")

  @Deprecated("Not OSI approved")
  fun `diffmark`() =
    licenseBuilder.license("diffmark license", "https://spdx.org/licenses/diffmark.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-4-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial 4.0 International", "https://spdx.org/licenses/CC-BY-NC-4.0.html")

  @Deprecated("Not OSI approved")
  fun `SHL-0-51`() =
    licenseBuilder.license("Solderpad Hardware License, Version 0.51", "https://spdx.org/licenses/SHL-0.51.html")

  @Deprecated("Not OSI approved")
  fun `IJG`() =
    licenseBuilder.license("Independent JPEG Group License", "https://spdx.org/licenses/IJG.html")

  @Deprecated("Not OSI approved")
  fun `Giftware`() =
    licenseBuilder.license("Giftware License", "https://spdx.org/licenses/Giftware.html")

  @Deprecated("Not OSI approved")
  fun `JPNIC`() =
    licenseBuilder.license("Japan Network Information Center License", "https://spdx.org/licenses/JPNIC.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-3-0-IGO`() =
    licenseBuilder.license("Creative Commons Attribution 3.0 IGO", "https://spdx.org/licenses/CC-BY-3.0-IGO.html")

  fun `MirOS`() =
    licenseBuilder.license("The MirOS Licence", "https://spdx.org/licenses/MirOS.html")

  @Deprecated("Not OSI approved")
  fun `BSD-4-Clause-Shortened`() =
    licenseBuilder.license("BSD 4 Clause Shortened", "https://spdx.org/licenses/BSD-4-Clause-Shortened.html")

  fun `OSL-2-1`() =
    licenseBuilder.license("Open Software License 2.1", "https://spdx.org/licenses/OSL-2.1.html")

  @Deprecated("Not OSI approved")
  fun `OFL-1-0`() =
    licenseBuilder.license("SIL Open Font License 1.0", "https://spdx.org/licenses/OFL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-1-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 1.0 Generic", "https://spdx.org/licenses/CC-BY-NC-SA-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CDLA-Permissive-1-0`() =
    licenseBuilder.license("Community Data License Agreement Permissive 1.0", "https://spdx.org/licenses/CDLA-Permissive-1.0.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-4`() =
    licenseBuilder.license("Open LDAP Public License v2.4", "https://spdx.org/licenses/OLDAP-2.4.html")

  @Deprecated("Not OSI approved")
  fun `OGL-Canada-2-0`() =
    licenseBuilder.license("Open Government Licence - Canada", "https://spdx.org/licenses/OGL-Canada-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-2-0`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 2.0 Generic", "https://spdx.org/licenses/CC-BY-SA-2.0.html")

  fun `Unlicense`() =
    licenseBuilder.license("The Unlicense", "https://spdx.org/licenses/Unlicense.html")

  fun `UCL-1-0`() =
    licenseBuilder.license("Upstream Compatibility License v1.0", "https://spdx.org/licenses/UCL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `LZMA-SDK-9-11-to-9-20`() =
    licenseBuilder.license("LZMA SDK License (versions 9.11 to 9.20)", "https://spdx.org/licenses/LZMA-SDK-9.11-to-9.20.html")

  fun `NTP`() =
    licenseBuilder.license("NTP License", "https://spdx.org/licenses/NTP.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-3-0-AT`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 3.0 Austria", "https://spdx.org/licenses/CC-BY-SA-3.0-AT.html")

  @Deprecated("Not OSI approved")
  fun `TCP-wrappers`() =
    licenseBuilder.license("TCP Wrappers License", "https://spdx.org/licenses/TCP-wrappers.html")

  @Deprecated("Not OSI approved")
  fun `Dotseqn`() =
    licenseBuilder.license("Dotseqn License", "https://spdx.org/licenses/Dotseqn.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 only", "https://spdx.org/licenses/GFDL-1.1-only.html")

  @Deprecated("Not OSI approved")
  fun `SMPPL`() =
    licenseBuilder.license("Secure Messaging Protocol Public License", "https://spdx.org/licenses/SMPPL.html")

  fun `GPL-3-0-or-later`() =
    licenseBuilder.license("GNU General Public License v3.0 or later", "https://spdx.org/licenses/GPL-3.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-invariants-only`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 only - invariants", "https://spdx.org/licenses/GFDL-1.1-invariants-only.html")

  @Deprecated("Not OSI approved")
  fun `Parity-7-0-0`() =
    licenseBuilder.license("The Parity Public License 7.0.0", "https://spdx.org/licenses/Parity-7.0.0.html")

  @Deprecated("Not OSI approved")
  fun `CDLA-Permissive-2-0`() =
    licenseBuilder.license("Community Data License Agreement Permissive 2.0", "https://spdx.org/licenses/CDLA-Permissive-2.0.html")

  @Deprecated("Not OSI approved")
  fun `OPL-1-0`() =
    licenseBuilder.license("Open Public License v1.0", "https://spdx.org/licenses/OPL-1.0.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-2-1+`() =
    licenseBuilder.license("GNU Library General Public License v2.1 or later", "https://spdx.org/licenses/LGPL-2.1+.html")

  @Deprecated("Deprecated License Id")
  fun `bzip2-1-0-5`() =
    licenseBuilder.license("bzip2 and libbzip2 License v1.0.5", "https://spdx.org/licenses/bzip2-1.0.5.html")

  @Deprecated("Not OSI approved")
  fun `BSD-4-Clause`() =
    licenseBuilder.license("BSD 4-Clause \"Original\" or \"Old\" License", "https://spdx.org/licenses/BSD-4-Clause.html")

  @Deprecated("Not OSI approved")
  fun `MS-LPL`() =
    licenseBuilder.license("Microsoft Limited Public License", "https://spdx.org/licenses/MS-LPL.html")

  fun `GPL-2-0-or-later`() =
    licenseBuilder.license("GNU General Public License v2.0 or later", "https://spdx.org/licenses/GPL-2.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `EPICS`() =
    licenseBuilder.license("EPICS Open License", "https://spdx.org/licenses/EPICS.html")

  @Deprecated("Not OSI approved")
  fun `W3C-19980720`() =
    licenseBuilder.license("W3C Software Notice and License (1998-07-20)", "https://spdx.org/licenses/W3C-19980720.html")

  @Deprecated("Not OSI approved")
  fun `xinetd`() =
    licenseBuilder.license("xinetd License", "https://spdx.org/licenses/xinetd.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-1-0`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 1.0 Generic", "https://spdx.org/licenses/CC-BY-SA-1.0.html")

  @Deprecated("Not OSI approved")
  fun `GPL-1-0-or-later`() =
    licenseBuilder.license("GNU General Public License v1.0 or later", "https://spdx.org/licenses/GPL-1.0-or-later.html")

  @Deprecated("Not OSI approved")
  fun `ClArtistic`() =
    licenseBuilder.license("Clarified Artistic License", "https://spdx.org/licenses/ClArtistic.html")

  @Deprecated("Not OSI approved")
  fun `Noweb`() =
    licenseBuilder.license("Noweb License", "https://spdx.org/licenses/Noweb.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-3-0`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 3.0 Unported", "https://spdx.org/licenses/CC-BY-NC-SA-3.0.html")

  @Deprecated("Not OSI approved")
  fun `SWL`() =
    licenseBuilder.license("Scheme Widget Library (SWL) Software License Agreement", "https://spdx.org/licenses/SWL.html")

  @Deprecated("Not OSI approved")
  fun `SSPL-1-0`() =
    licenseBuilder.license("Server Side Public License, v 1", "https://spdx.org/licenses/SSPL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-SA-4-0`() =
    licenseBuilder.license("Creative Commons Attribution Share Alike 4.0 International", "https://spdx.org/licenses/CC-BY-SA-4.0.html")

  fun `ZPL-2-1`() =
    licenseBuilder.license("Zope Public License 2.1", "https://spdx.org/licenses/ZPL-2.1.html")

  @Deprecated("Deprecated License Id")
  fun `GPL-2-0-with-classpath-exception`() =
    licenseBuilder.license("GNU General Public License v2.0 w/Classpath exception", "https://spdx.org/licenses/GPL-2.0-with-classpath-exception.html")

  fun `BSD-3-Clause`() =
    licenseBuilder.license("BSD 3-Clause \"New\" or \"Revised\" License", "https://spdx.org/licenses/BSD-3-Clause.html")

  fun `Zlib`() =
    licenseBuilder.license("zlib License", "https://spdx.org/licenses/Zlib.html")

  @Deprecated("Deprecated License Id")
  fun `LGPL-3-0+`() =
    licenseBuilder.license("GNU Lesser General Public License v3.0 or later", "https://spdx.org/licenses/LGPL-3.0+.html")

  @Deprecated("Not OSI approved")
  fun `TU-Berlin-2-0`() =
    licenseBuilder.license("Technische Universitaet Berlin License 2.0", "https://spdx.org/licenses/TU-Berlin-2.0.html")

  @Deprecated("Not OSI approved")
  fun `Latex2e`() =
    licenseBuilder.license("Latex2e License", "https://spdx.org/licenses/Latex2e.html")

  fun `BSD-2-Clause`() =
    licenseBuilder.license("BSD 2-Clause \"Simplified\" License", "https://spdx.org/licenses/BSD-2-Clause.html")

  @Deprecated("Not OSI approved")
  fun `TORQUE-1-1`() =
    licenseBuilder.license("TORQUE v2.5+ Software License v1.1", "https://spdx.org/licenses/TORQUE-1.1.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-2-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.2 or later - invariants", "https://spdx.org/licenses/GFDL-1.2-invariants-or-later.html")

  @Deprecated("Not OSI approved")
  fun `PSF-2-0`() =
    licenseBuilder.license("Python Software Foundation License 2.0", "https://spdx.org/licenses/PSF-2.0.html")

  @Deprecated("Not OSI approved")
  fun `SAX-PD`() =
    licenseBuilder.license("Sax Public Domain Notice", "https://spdx.org/licenses/SAX-PD.html")

  fun `MPL-2-0-no-copyleft-exception`() =
    licenseBuilder.license("Mozilla Public License 2.0 (no copyleft exception)", "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html")

  fun `AFL-1-2`() =
    licenseBuilder.license("Academic Free License v1.2", "https://spdx.org/licenses/AFL-1.2.html")

  @Deprecated("Not OSI approved")
  fun `SGI-B-1-0`() =
    licenseBuilder.license("SGI Free Software License B v1.0", "https://spdx.org/licenses/SGI-B-1.0.html")

  @Deprecated("Not OSI approved")
  fun `LZMA-SDK-9-22`() =
    licenseBuilder.license("LZMA SDK License (versions 9.22 and beyond)", "https://spdx.org/licenses/LZMA-SDK-9.22.html")

  @Deprecated("Not OSI approved")
  fun `ZPL-1-1`() =
    licenseBuilder.license("Zope Public License 1.1", "https://spdx.org/licenses/ZPL-1.1.html")

  fun `Entessa`() =
    licenseBuilder.license("Entessa Public License v1.0", "https://spdx.org/licenses/Entessa.html")

  @Deprecated("Not OSI approved")
  fun `BSD-3-Clause-No-Nuclear-License-2014`() =
    licenseBuilder.license("BSD 3-Clause No Nuclear License 2014", "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html")

  @Deprecated("Not OSI approved")
  fun `XSkat`() =
    licenseBuilder.license("XSkat License", "https://spdx.org/licenses/XSkat.html")

  @Deprecated("Not OSI approved")
  fun `NLPL`() =
    licenseBuilder.license("No Limit Public License", "https://spdx.org/licenses/NLPL.html")

  @Deprecated("Not OSI approved")
  fun `libselinux-1-0`() =
    licenseBuilder.license("libselinux public domain notice", "https://spdx.org/licenses/libselinux-1.0.html")

  fun `Fair`() =
    licenseBuilder.license("Fair License", "https://spdx.org/licenses/Fair.html")

  @Deprecated("Not OSI approved")
  fun `Xerox`() =
    licenseBuilder.license("Xerox License", "https://spdx.org/licenses/Xerox.html")

  @Deprecated("Not OSI approved")
  fun `X11-distribute-modifications-variant`() =
    licenseBuilder.license("X11 License Distribution Modification Variant", "https://spdx.org/licenses/X11-distribute-modifications-variant.html")

  fun `CDDL-1-0`() =
    licenseBuilder.license("Common Development and Distribution License 1.0", "https://spdx.org/licenses/CDDL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Unicode-TOU`() =
    licenseBuilder.license("Unicode Terms of Use", "https://spdx.org/licenses/Unicode-TOU.html")

  @Deprecated("Not OSI approved")
  fun `CECILL-1-0`() =
    licenseBuilder.license("CeCILL Free Software License Agreement v1.0", "https://spdx.org/licenses/CECILL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `D-FSL-1-0`() =
    licenseBuilder.license("Deutsche Freie Software Lizenz", "https://spdx.org/licenses/D-FSL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `Barr`() =
    licenseBuilder.license("Barr License", "https://spdx.org/licenses/Barr.html")

  @Deprecated("Not OSI approved")
  fun `GFDL-1-1-invariants-or-later`() =
    licenseBuilder.license("GNU Free Documentation License v1.1 or later - invariants", "https://spdx.org/licenses/GFDL-1.1-invariants-or-later.html")

  @Deprecated("Not OSI approved")
  fun `TCL`() =
    licenseBuilder.license("TCL/TK License", "https://spdx.org/licenses/TCL.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-2-2`() =
    licenseBuilder.license("Open LDAP Public License 2.2.2", "https://spdx.org/licenses/OLDAP-2.2.2.html")

  @Deprecated("Not OSI approved")
  fun `SHL-0-5`() =
    licenseBuilder.license("Solderpad Hardware License v0.5", "https://spdx.org/licenses/SHL-0.5.html")

  @Deprecated("Not OSI approved")
  fun `CECILL-2-0`() =
    licenseBuilder.license("CeCILL Free Software License Agreement v2.0", "https://spdx.org/licenses/CECILL-2.0.html")

  fun `AFL-2-0`() =
    licenseBuilder.license("Academic Free License v2.0", "https://spdx.org/licenses/AFL-2.0.html")

  @Deprecated("Not OSI approved")
  fun `CC-BY-NC-SA-3-0-IGO`() =
    licenseBuilder.license("Creative Commons Attribution Non Commercial Share Alike 3.0 IGO", "https://spdx.org/licenses/CC-BY-NC-SA-3.0-IGO.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-6`() =
    licenseBuilder.license("Open LDAP Public License v2.6", "https://spdx.org/licenses/OLDAP-2.6.html")

  @Deprecated("Not OSI approved")
  fun `OLDAP-2-5`() =
    licenseBuilder.license("Open LDAP Public License v2.5", "https://spdx.org/licenses/OLDAP-2.5.html")

  fun `Artistic-1-0-Perl`() =
    licenseBuilder.license("Artistic License 1.0 (Perl)", "https://spdx.org/licenses/Artistic-1.0-Perl.html")

  fun `CAL-1-0`() =
    licenseBuilder.license("Cryptographic Autonomy License 1.0", "https://spdx.org/licenses/CAL-1.0.html")

  @Deprecated("Not OSI approved")
  fun `BSD-2-Clause-Views`() =
    licenseBuilder.license("BSD 2-Clause with views sentence", "https://spdx.org/licenses/BSD-2-Clause-Views.html")

  @Deprecated("Not OSI approved")
  fun `gSOAP-1-3b`() =
    licenseBuilder.license("gSOAP Public License v1.3b", "https://spdx.org/licenses/gSOAP-1.3b.html")

  @Deprecated("Not OSI approved")
  fun `Minpack`() =
    licenseBuilder.license("Minpack License", "https://spdx.org/licenses/Minpack.html")

  fun `NPOSL-3-0`() =
    licenseBuilder.license("Non-Profit Open Software License 3.0", "https://spdx.org/licenses/NPOSL-3.0.html")

}
