import os
import urllib.request as req
import shlex
import json

with req.urlopen("https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json") as c:
    data = json.load(c)

# space between @ and generated so that this script isn't detected as generated
print("// Automatically @" "generated by " + os.path.basename(__file__))
print("package moe.nea.licenseextractificator.builder")
print()
print("/**")
print(" * An automatically generated file for all known SPDX license identifiers.")
print(" * You will need to make use of Kotlins backtick notation for most of the license identifiers.")
print(" * Dots in the license identifiers have been replaced with dashes, as to compliant with the JVM")
print(" * ")
print(" * Data last updated " + str(data['releaseDate']) + ".")
print(" */")
print("class DefaultLicenses(val licenseBuilder: LicenseBuilder) {")

for license in data['licenses']:
    if license['isDeprecatedLicenseId']:
        print("  @Deprecated(\"Deprecated License Id\")")
    elif not license['isOsiApproved']:
        print("  @Deprecated(\"Not OSI approved\")")
    print("  fun `"+license['licenseId'].replace('.', '-')+"`() =")
    print("    licenseBuilder.license("
          + json.dumps(license["name"]) + ", "
          + json.dumps(license['reference']) + ")")
    print()

print("}")
